name: logchain
description: Binance-based crypto monitoring & comparing application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  share_plus: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  cached_network_image: ^3.2.0
  candlesticks: ^1.1.1
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: 1.2.3
  google_fonts: ^2.1.0
  modal_bottom_sheet: ^2.0.0
  provider: 6.0.1
  skeletons: any
  cupertino_back_gesture: 0.1.0

  injectable: 1.5.0
  json_serializable: ^6.1.1
  dio: ^4.0.4

  freezed: ^0.14.5
  freezed_annotation: ^1.0.0

  build_runner: ^2.1.5
  hive: ^2.0.4
  hive_flutter: ^1.1.0


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"


flutter:
  uses-material-design: true

  assets:
    - assets/icon.png
    - assets/icons/menu_icon.png
